version: '3.9'

services:
  postgres:
    image: postgres
    container_name: pdf-ai
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5555:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - redis_insight_volume_data:/db

volumes:
  pgadmin-data:
  pgdata:
  redis:
  redis_insight_volume_data:
